routes/web.php
<?php

use App\Http\Controllers\Cities\CityController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Settings\SettingController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
   return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('cities',CityController::class);
    Route::resource('users',UserController::class);
    Route::any('settings',SettingController::class);
});

app/Models/User.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Users/UserController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Models\User;
use App\Services\Users\UserService as Service;
use Illuminate\Http\JsonResponse;

class UserController extends Controller
{
    public function __construct()
    {
        $this->service = app(Service::class);
    }

    public function create(): JsonResponse
    {
        return $this->createElementModal();
    }

    public function store(StoreUserRequest $request): JsonResponse
    {
        return $this->storeElement($request->validated());
    }

    public function edit(User $user): JsonResponse
    {
        return $this->editElementModal($user);
    }

    public function show(User $user): JsonResponse
    {
        return $this->showElementModal($user);
    }

    public function update(StoreUserRequest $request, User $user): JsonResponse
    {
        return $this->updateElement($request->validated(), $user);
    }

    public function destroy(User $user): JsonResponse
    {
        return $this->destroyElement($user);
    }
}

resources/views/users/form.blade.php
<form id="create" method="POST" enctype="multipart/form-data" role="form">
    @csrf
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="name">Имя <sub class="text-danger">*</sub></label>
                    <input type="text" name="name" value="{{ $user->name ?? @old('name') }}" class="form-control" id="name" placeholder="Иван" required>
                </div>
                <div class="form-group">
                    <label for="email">Email <sub class="text-danger">*</sub></label>
                    <input type="email" name="email" value="{{ $user->email ?? @old('email') }}" class="form-control" id="email" placeholder="mail@mail.ru" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль <sub class="text-danger">*</sub></label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                           placeholder="Password" required>
                </div>
                <div class="form-group">
                    <label for="password_confirmation">Повторите пароль <sub class="text-danger">*</sub></label>
                    <input type="password" name="password_confirmation" class="form-control" id="password_confirmation"
                           placeholder="Confirm Password" required>
                </div>

            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0)" class="btn btn-success modal-button-form"
           @if(isset($user)) onclick="Main.updateRecord('{{ route('users.update', $user->id) }}')"
           @else onclick="Main.storeRecord('{{ route('users.store') }}')" @endif
        >Сохранить и добавить</a>
        <button type="button" class="btn btn-danger" onclick="Main.dissmissModal('#form')">Отмена</button>
    </div>
</form>

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="page-title">
        <h2 class="text-md text-highlight">{{ $title }}</h2>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <button type="button" class="btn btn-success"
                                    onclick="Main.createRecord('{{ route('users.create') }}')">
                                {{ __('users.create.title') }}
                            </button>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-4">
                            <input type="text" class="form-control" placeholder="{{ __('users.search.title') }}"
                                   onkeyup="Main.searchDataTable(dtListelements, this);"
                                   onchange="Main.searchDataTable(dtListelements, this);" data-name="filter">
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <table style="width: 100%;" class="table table-theme table-row v-middle table-text" id="listelement-table">
                        <thead>
                        @if(!empty($columns))
                            <tr>
                                @foreach ($columns as $column)
                                    <th>{{ $column['column_name'] }}</th>
                                @endforeach
                            </tr>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        let dtListelements = $('#listelement-table').DataTable(Object.assign({
            ajax: {
                url: "{{ route('users.index') }}",
                data: function (d) {
                },
                error: function (data) {
                    toastr.error('Ошибка загрузки данных для таблицы. Пожалуйста, перезагрузите страницу');
                },
            },
            columns: {!! $jsonColumns !!},
            sDom: '<"top">rt<"bottom"p><"clear">',
        }, Main.commonConfigDt));

        dtListelements.on('draw', function () {
            Main.showModalElementDataTable('listelement-table');
        });
    </script>
@endsection