routes/web.php
<?php

use App\Http\Controllers\Cities\CityController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Settings\SettingController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
   return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('cities',CityController::class);
    Route::resource('users',UserController::class);
    Route::any('settings',SettingController::class);
});

app/Models/Cities/City.php
<?php

declare(strict_types=1);

namespace App\Models\Cities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'code',
        'weather',
    ];
}

app/Http/Controllers/Cities/CityController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Cities;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCityRequest;
use App\Models\Cities\City;
use App\Services\Cities\CityService as Service;
use Illuminate\Http\JsonResponse;

class CityController extends Controller
{
    public function __construct()
    {
        $this->service = app(Service::class);
    }

    public function create(): JsonResponse
    {
        return $this->createElementModal();
    }

    public function store(StoreCityRequest $request): JsonResponse
    {
        return $this->storeElement($request->validated());
    }

    public function edit(City $city): JsonResponse
    {
        return $this->editElementModal($city);
    }

    public function show(City $city): JsonResponse
    {
        return $this->showElementModal($city);
    }

    public function update(StoreCityRequest $request, City $city): JsonResponse
    {
        return $this->updateElement($request->validated(), $city);
    }

    public function destroy(City $city): JsonResponse
    {
        return $this->destroyElement($city);
    }
}

resources/views/cities/form.blade.php
<form id="create" method="POST" enctype="multipart/form-data" role="form">
    @csrf
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Название<sup class="text-danger">*</sup></label>
                    <input name="name" type="text" class="form-control" placeholder="Москва" required
                           value="{{ $city->name ?? old('title') }}"
                    >
                </div>
                <div class="form-group">
                    <label>Код</label>
                    <input name="code" type="text" class="form-control" placeholder="код города" required
                           value="{{ $city->code ?? old('code') }}"
                    >
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0)" class="btn btn-success modal-button-form"
           @if(isset($city)) onclick="Main.updateRecord('{{ route('cities.update', $city->id) }}')"
           @else onclick="Main.storeRecord('{{ route('cities.store') }}')" @endif
        >Сохранить и добавить</a>
        <button type="button" class="btn btn-danger" onclick="Main.dissmissModal('#form')">Отмена</button>
    </div>
</form>

resources/views/cities/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="page-title">
        <h2 class="text-md text-highlight">{{ $title }}</h2>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <button type="button" class="btn btn-success"
                                    onclick="Main.createRecord('{{ route('cities.create') }}')">
                                {{ __('cities.create.title') }}
                            </button>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-4">
                            <input type="text" class="form-control" placeholder="{{ __('cities.search.title') }}"
                                   onkeyup="Main.searchDataTable(dtListelements, this);"
                                   onchange="Main.searchDataTable(dtListelements, this);" data-name="filter">
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <table style="width: 100%;" class="table table-theme table-row v-middle table-text" id="listelement-table">
                        <thead>
                        @if(!empty($columns))
                            <tr>
                                @foreach ($columns as $column)
                                    <th>{{ $column['column_name'] }}</th>
                                @endforeach
                            </tr>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        let dtListelements = $('#listelement-table').DataTable(Object.assign({
            ajax: {
                url: "{{ route('cities.index') }}",
                data: function (d) {
                },
                error: function (data) {
                    toastr.error('Ошибка загрузки данных для таблицы. Пожалуйста, перезагрузите страницу');
                },
            },
            columns: {!! $jsonColumns !!},
            sDom: '<"top">rt<"bottom"p><"clear">',
        }, Main.commonConfigDt));

        dtListelements.on('draw', function () {
            Main.showModalElementDataTable('listelement-table');
        });
    </script>
@endsection